### ISSUE TITLE
-line-count option skips some tests and run other tests twice

### ISSUE THREAD

**Issue by curpeng** [leonid-shevtsov/split_tests#3] opened 2017-05-29 11:27 UTC
We run test build with 4 groups in such way:

```
bundle exec rspec $(./split_tests -line-count -split-index=0 -split-total=4) --color --tty
bundle exec rspec $(./split_tests -line-count -split-index=1 -split-total=4) --color --tty
bundle exec rspec $(./split_tests -line-count -split-index=2 -split-total=4) --color --tty
bundle exec rspec $(./split_tests -line-count -split-index=3 -split-total=4) --color --tty
```
and we noticed that our tests sometimes are broken after merging even if branch was rebased with develop and latest test build was green. We turned on documentation format for rspec and saw that some tests are executed twice and some tests are missed.

**Comment by leonid-shevtsov** [comment] 2020-05-15 17:34
this was probably caused by bugs in zglob. closing for old age, but i'll keep an eye on our test suite.

**Closed as completed by leonid-shevtsov** 2020-05-15 17:34 UTC
